name: GenerateCV
on:
  push:
    branches: [main]
jobs:
  generate-cv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate CV
        run: docker-compose up --build
      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/2024-01-10_0.1.0',
              sha: context.sha
            })
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "output/*.pdf"
          body: "release 2024-01-10_0.1.0"
          tag: "2024-01-10_0.1.0"
