name: GenerateCV
on:
  push:
    branches: [ main ]
jobs:
  generate-cv:
    runs-on: ubuntu-latest
    container: python:3.8.18-bullseye
    steps:
      - name: Install latex
        run: apt update && apt install texlive-full -y && apt install xzdec && apt install wget
      - name: Setup latex
        run: tlmgr init-usertree
      - uses: actions/checkout@v4
      - name: Install requirements
        run: python -m pip install -r requirements.txt
      - name: Generate CV
        run: python generate.py
      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/2024-01-10_0.1.0',
              sha: context.sha
            })
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "output/*.pdf"
          body: "release 2024-01-10_0.1.0"
          tag: "2024-01-10_0.1.0"
