name: GenerateCV
on:
  push:
    branches: [ main ]
jobs:
  generate-cv:
    runs-on: ubuntu-latest
    container: python:3.8.18-bullseye
    steps:
      - name: Install latex
        run: apt update && apt install texlive-full -y && apt install xzdec && apt install wget
      - name: Setup latex
        run: tlmgr init-usertree
      - uses: actions/checkout@v4
      - name: Install requirements
        run: python -m pip install -r requirements.txt
      - name: Generate CV
        run: python generate.py
      - name: Archive CV
        uses: actions/upload-artifact@v3
        with:
          name: cv
          path: output
